# PyTorch Functions

In this notebook, we will discuss about some Tensor function by PyTorch. These are simple PyTorch function which are vvery helpful in modifying the arrays or matrices using tensors.

These are some PyTorch functions which are illustrated in the following code:
- torch.narrow()
- torch.expand()
- index_copy_()
- torch.permute()
- torch.repeat()

In [1]:
# Import torch and other required modules
#!pip install torch
import torch.tensor

## Function 1 - torch.narrow()

torch.narrow is a tensor function which is used to narrow down a multidimensional matrix in a desired form by taking its dimension,starting point and length.

Syntax: variable.narrow(dimension, starting, length)

In [2]:
# Example 1 - working
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x.narrow(1, 1, 2)

tensor([[2, 3],
        [5, 6],
        [8, 9]])

In the above example, the dimension is set ot 1, so the number of columns is 3 (Starting from 0th position)
then the starting point is selected as 1, so it selects the 2nd and 3rd element (starting from 0th position)
then the length is set to 2, so number of rows is 3 (from 0th position).

Similarly, taking some more examples:

In [3]:
# Example 2 - working
x = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.narrow(1, 0, 4)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [4]:
# Example 3 - breaking (to illustrate when it breaks)
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x.narrow(0, 1, 3)

RuntimeError: start (1) + length (3) exceeds dimension size (3).

Also in the above example, taking a values more than the original (dimension, length or breadth) can throw an exception.

## Function 2 - torch.expand()

torch.expand() is used to expand a given matrix in bigger size by increasing its columns.
It is just the opposite of torch.narrow()
But it only expands from a single dimensional array.

Syntax: variable.expand(old_cloumns, new_columns)

In [5]:
# Example 1 - working
x = torch.tensor([[1], [2], [3]])
x.size()

torch.Size([3, 1])

In [6]:
print(x.expand(3, 4))

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])


Now in the above example we can see that the matrix on have total of 3 values.
Using tensor.exapnd() it duplicates the same values in desired number of rows and columns.
The number of rows is 3 and columns is 4, so it makes a 3x4 matrix by duplication of values

Similarly, taking a few examples for better understanding:

In [7]:
# Example 2 - working
x = torch.tensor([[1], [2], [3]])
x.expand(3, 10)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

Explanation about example

In [8]:
# Example 3 - breaking (to illustrate when it breaks)
x = torch.tensor([[1,2], [2,4], [3,6]])
x.expand(2, 4)

RuntimeError: The expanded size of the tensor (4) must match the existing size (2) at non-singleton dimension 1.  Target sizes: [2, 4].  Tensor sizes: [3, 2]

In the above example, the matrix is not a single dimnesional matrix, so it shows traceback

## Function 3 - index_copy_()

Copies the elements of tensor into the self tensor by selecting the indices in the order given in index. For example, if dim == 0 and index[i] == j, then the ith row of tensor is copied to the jth row of self.

Syntax: variable.index_copy_(dimension, index, tensor)

In [9]:
# Example 1 - working
x = torch.zeros(5, 3)
t = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float)
index = torch.tensor([0, 3, 2])
x.index_copy_(0, index, t)

tensor([[1., 2., 3.],
        [0., 0., 0.],
        [7., 8., 9.],
        [4., 5., 6.],
        [0., 0., 0.]])

For the given example,
dim (int) – dimension along which to index
index (LongTensor) – indices of tensor to select from
tensor (Tensor) – the tensor containing values to copy

Taking a few examples:

In [10]:
# Example 2 - working
x = torch.zeros(7, 3)
t = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float)
index = torch.tensor([0, 2, 6])
x.index_copy_(0, index, t)

tensor([[1., 2., 3.],
        [0., 0., 0.],
        [4., 5., 6.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [7., 8., 9.]])

In [11]:
# Example 3 - breaking (to illustrate when it breaks)
x = torch.zeros(5, 3)
t = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float)
index = torch.tensor([0, 3, 5])
x.index_copy_(0, index, t)

RuntimeError: invalid argument 3: out of range at /opt/conda/conda-bld/pytorch_1587428266983/work/aten/src/TH/generic/THTensor.cpp:233

In taking the value out of range can throw a traceback

## Function 4 - torch.permute()

torch.permute() is used to rearrange the elements present in the tensor. But with this we cannot rearrange the tensor arrays.
Returns a view of the original tensor with its dimensions permuted.

Syntax: variable.permute(rearanging_position).size()

In [12]:
# Example 1 - working
x = torch.randn(2, 3, 5, 8)
x.size()
x.permute(2, 0, 1, 3).size()

torch.Size([5, 2, 3, 8])

In the given example, the parameters in the permute function is the order in which we want to rearrange the elements of the variable. Therefore we need to keep in mind that the parameters is in proper range.

In [13]:
# Example 2 - working
x = torch.randn(2, 3, 5, 8, 10)
x.size()
x.permute(2, 0, 4, 1, 3).size()

torch.Size([5, 2, 10, 3, 8])

In [14]:
# Example 3 - breaking (to illustrate when it breaks)
x = torch.randn(2, 3, 5, 8)
x.size()
x.permute(2, 0, 1, 4).size()

IndexError: Dimension out of range (expected to be in range of [-4, 3], but got 4)

The parameters of permute function should be in range from 0 to n-1, where n is number of elements in the tensor. If the numbers are out of range or extra number of parameters are provided, then the program will throw traceback error.

## Function 5 - torch.repeat()

This funciton is also used to expand the elements in the tensor array. But here it exapnd the matrix by exapnding both rows and columns.

Syntax: variable.repeat(duplication_of_rows, duplication_of_columns)

In [15]:
# Example 1 - working
x = torch.tensor([1, 2, 3])
x.repeat(4, 3)

tensor([[1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3]])

Here, the first parameter shows how many times the rows will be repeated. Here the values is 4 and so it repeat the rows four times. The second parameter shows how many times the elements in array will be repeated columnwise.

Taking some more examples for better illustration:

In [16]:
# Example 2 - working
x = torch.tensor([1, 2, 3, 4, 5])
x.repeat(5, 2)

tensor([[1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]])

In [17]:
# Example 3 - breaking (to illustrate when it breaks)
x = torch.tensor([1, 2, 3],[4, 5, 6])
x.repeat(10, -1)

TypeError: tensor() takes 1 positional argument but 2 were given

The above function will throw a traceback if we put more than one row. The column has no limitation but the number row is limited ot single. 

## Conclusion

In this notebook I discussed some simple Tensor.torch functions which can help a lot. These are simple functions but are very helpful in arranging and modifying the arrays which help for Deep Learning and Data Science.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html

In [18]:
!pip install jovian --upgrade --quiet

In [19]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
